use_frameworks!

platform :ios, '10.0'

target 'YYYLib_Example' do
  pod 'YYYLib', :path => '../'

  target 'YYYLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
